const mongoose = require("mongoose");

const homepageWidgetSchema = new mongoose.Schema({
  categorylist: {
    category_ref: [{ type: mongoose.Schema.Types.ObjectId, ref: "Category" }],
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
  },
  template2: {
    category_ref: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
  },
  template3: {
    category_ref: { type: mongoose.Schema.Types.ObjectId, ref: "Banner" },
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
  },
  template4: {
    category_ref: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
  },
  template5: {
    category_ref: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
  },
  template6: {
    category_ref: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
  },
  template7: {
    category_ref: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
    title: { type: String, required: true },
    des: { type: String, required: true },
    image: { type: String, required: true },
  },
  template8: {
    category_ref: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
  },
  template9: {
    category_ref: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
  },
  template10: {
    category_ref: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
  },
  template11: {
    category_ref: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
  },
  template12: {
    category_ref: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
  },
  template13: {
    category_ref: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
  },
  template14: {
    category_ref: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
    title: { type: String, required: true },
    des: { type: String, required: true },
    image: { type: String, required: true },
  },
  template15: {
    category_ref: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
  },
  template16: {
    category_ref: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
  },
  template17: {
    category_ref: [{ type: mongoose.Schema.Types.ObjectId, ref: "Banner" }],
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
  },
  template18: {
    category_ref: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
  },
  template19: {
    category_ref: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
  },
  template20: {
    category_ref: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
  },
  template21: {
    category_ref: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
    title: { type: String, required: true },
    des: { type: String, required: true },
    image: { type: String, required: true },
  },
  template22: {
    category_ref: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
  },
  template23: {
    category_ref: [{ type: mongoose.Schema.Types.ObjectId, ref: "Banner" }],
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
  },
  template24: {
    category_ref: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
  },
  template25: {
    category_ref: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
  },
  template26: {
    category_ref: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
  },
  template27: {
    category_ref: { type: mongoose.Schema.Types.ObjectId, ref: "Category" },
    background_color: { type: String, required: true },
    title_color: { type: String, required: true },
    subcategory_color: { type: String, required: true },
    ui_order_number: { type: String, required: true },
    show_Category: { type: Boolean, required: true },
  },
});

const HomepageWidget = mongoose.model("HomepageWidget", homepageWidgetSchema);

module.exports = HomepageWidget;
